# Generated by Django 4.0.6 on 2022-09-02 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiroNome', models.CharField(max_length=250)),
                ('sobrenome', models.CharField(max_length=250)),
                ('imagem', models.ImageField(upload_to='imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('modalidade', models.CharField(choices=[('Bacharelado', 'Bacharelado'), ('Licenciatura', 'Licenciatura'), ('Tecnológo', 'Tecnológo')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiroNome', models.CharField(max_length=250)),
                ('sobrenome', models.CharField(max_length=250)),
                ('linkCurriculoLattes', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('anoDocumento', models.IntegerField(verbose_name='anoDocumento')),
                ('resumo', models.TextField(max_length=300)),
                ('arquivo', models.FileField(upload_to='tccs')),
                ('palavrasChave', models.CharField(max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc.autor')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc.curso')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc.orientador')),
            ],
        ),
    ]
